config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'home/generate_ipsum', to: "home#generate_ipsum", as: :generate_ipsum
  patch 'home/generate_ipsum', to: "home#generate_ipsum"
  resources :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
  validate :has_lyrics
  validates_uniqueness_of :title

  def has_lyrics
    fetcher = Lyricfy::Fetcher.new
    begin
      fetcher.search("David Bowie", title)
      true
    rescue
      errors.add(:base, 'no lyrics available!')
    end
  end

  def self.all_alphabetized
    Song.all.order(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @songs = Song.all_alphabetized
    if @songs.length > 0
      Ipsum.fill_dictionary if !$markov
      @tagline = $markov.generate_2_sentences
    end
    @song = Song.new()
  end

  def generate_ipsum
    render json: { text: $markov.generate_4_sentences }
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def create
    @song = Song.new(params.require(:song).permit(:title))
    if @song.save
      Ipsum.add_song(@song)
      redirect_to root_path, notice: "Added #{@song.title} to BowieIpsum dictionary!"
    else
      redirect_to root_path, notice: @song.errors.full_messages.first
    end
  end

  def index
    songs = Song.all
    @songs_first = songs[0...songs.length/2]
    @songs_last = songs[songs.length/2..-1]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/home/index.html.erb
<!-- Header -->
<header>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <img class="img-responsive" src="<%= asset_path( 'bowiebot.png' ) %>" alt="">
        <div class="intro-text">
          <span class="name">BowieIpsum</span>
          <hr class="star-light">
          <span class="skills"><%= @tagline %></span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Generate Ipsum Section -->
<section id="generate-ipsum">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>generate ipsum</h2>
        <hr class="star-primary">
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4 generate-ipsum-form">
        <div class="ipsum-control">
          <%= button_to "Generate Ipsum", generate_ipsum_path, form_class: "form-horizontal", class: "btn btn-success btn-md btn-block generate-ipsum-button" %>
          <%= button_to "Remove Ipsum", "#",  form_class: "form-horizontal", class: "btn btn-danger btn-md btn-block remove-ipsum-button", role: "button" %>
          <%= button_to "Clear", "#", form_class: "form-horizontal", class: "btn btn-default btn-md btn-block clear-ipsum-button", role: "button"  %>
        </div>

        <div class="add-song form-group">
          <h3>Add a new song to the dictionary</h3>
          <%= form_for @song, html: {class: "form-inline"} do |f| %>
            <%= f.label :title, class: "form-label" %>:
            <%= f.text_field :title, class: "form-control" %>
            <%= f.submit "Add Song", class: "form-control btn btn-default btn-md" %>
          <% end %>
        </div>
        <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: name %>
        <% end -%>
      </div>
      <div class="col-sm-8 generate-ipsum-item">
        <div class="ipsum-well">
        </div>
      </div>
    </div>
  </div>
</section>

<!-- About Section -->
<section class="success" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>About</h2>
        <hr class="star-light">
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-lg-offset-2">
        <p>Hi, I'm Bri. I have an affinity for David Bowie, twitterbots
          (really, robots of any kind!), and natural language processing.
          I used a markov chain generator to create this ipsum model
          (inspired by <a href="http://joshmillard.com/garkov/">Garkov</a>!).</p>
      </div>
      <div class="col-lg-4">
        <p>You can add any Bowie song you like to the dictionary, as long as my
           code can grab the lyrics... this ipsum will learn from it. Look at a
           list of songs already in the dictionary
           <a href='javascript:void(0)' onClick="$('#my-cool-modal-window').modal()">here</a>.</p>
      </div>
    </div>
  </div>
</section>

<div id='my-cool-modal-window' class='modal fade' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true' >
  <div class='modal-dialog'>
    <div class='modal-content'>
      <%= render "songs/index" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BowieIpsum</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body id="page-top" class="index">

  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#page-top">BowieIpsum</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="hidden">
            <a href="#page-top"></a>
          </li>
          <li class="page-scroll">
            <a href="#generate-ipsum">Generate Ipsum</a>
          </li>
          <li class="page-scroll">
            <a href="#about">About</a>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>


  <%= yield %>


  <!-- Footer -->
  <footer class="text-center">
    <div class="footer-above">
      <div class="container">
        <div class="row">
          <div class="footer-col col-md-4">
            <h3>Location</h3>
            <p>Seattle, WA</p>
          </div>
          <div class="footer-col col-md-4">
            <h3>Around the Web</h3>
            <ul class="list-inline">
              <li>
                <a href="https://github.com/brigid2718" class="btn-social btn-outline"><i class="fa fa-fw fa-github"></i></a>
              </li>
              <li>
                <a href="https://twitter.com/bri616" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
              </li>
              <li>
                <a href="https://www.linkedin.com/pub/bri-dotson/74/137/9b6" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
              </li>
            </ul>
          </div>
          <div class="footer-col col-md-4">
            <h3>Thanks to the Noun Project</h3>
            <p>Robot icon above created by <a href="http://thenounproject.com/Julihan/">Julien Deveaux</a>. Reused and modified under Creative Commons – Attribution (CC BY 3.0). </p>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-below">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            Copyright &copy; Bri Dotson 2014
          </div>
        </div>
      </div>
    </div>
  </footer>

  <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
  <div class="scroll-top page-scroll visible-xs visble-sm">
    <a class="btn btn-primary" href="#page-top">
      <i class="fa fa-chevron-up"></i>
    </a>
  </div>

<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
</body>
</html>

app/views/songs/_index.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h3 id="myModalLabel">Bowie Ipsum's Songs</h3>
  <hr class="star-primary">
</div>
<div class="modal-body">
  <section class="success" id="songs">
    <div class="container">
      <div class="row">
          <% @songs.each do |song| %>
          <p><%= song.title %></p>
          <% end %>
      </div>
    </div>
  </section>
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal">Close</button>
</div>

app/views/songs/index.html.erb
<section class="success" id="songs">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>Bowie Ipsum's Songs</h2>
        <hr class="star-light">
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-lg-offset-2">
        <% @songs_first.each do |song| %>
          <p><%= song.title %></p>
        <% end %>
      </div>
      <div class="col-lg-4">
        <% @songs_last.each do |song| %>
          <p><%= song.title %></p>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/songs/index.js.erb
$("#modal-window).html("<%= escape_javascript(render 'songs/index') %>");